# customizable as needed. maybe explore multiple yaml files?

model:
  is_local: false
  model_dir: ""
  name: "meta-llama/Llama-3.2-3B-Instruct"
  architecture: "causal"        
  quantization: false
  tokenizer_pad_token: "eos_token"
  tokenizer_padding_side: "left"

peft:
  is_peft: false
  type: "lora"
  r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
    - "lm_head"
  task_type: "CAUSAL_LM"

bnb:
    is_bnb: false
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    bnb_4bit_compute_dtype: "bfloat16"

infer:
    save_path: "src/evaluation/results/methods2test/llama_3_2_3B"
    pred_label: "ORIGINAL" # "ORIGINAL | FINETUNED"

dataset:
  name: "mydataset"
  processed_path: "src/data/datasets/methods2test/processed/llama_3_2_3B/processed_test.json"
  need_special_processing: false
  special_processing_func: "llama_3_2_3B_template"
  split_seed: 42
  num_workers: 16
  batch_size: 512
  max_input_len: 720
  max_target_len: 256

misc:
  device: "cuda"
  notes: "experiment for Mistral7B with LoRA"
  log_dir: "logs/default"
  log_name: "meta-llama_3_2_3B.log"
