models:
  llama_3B:
    processed_train: "src/data/datasets/methods2test/processed/llama_3_2_3B/processed_train.json"
    processed_eval: "src/data/datasets/methods2test/processed/llama_3_2_3B/processed_eval.json"
    processed_test: "src/data/datasets/methods2test/processed/llama_3_2_3B/processed_test.json"
  qwen_coder:
    processed_train: "src/data/datasets/methods2test/processed/Qwen2_5-Coder-3B-Instruct/processed_train.json"
    processed_eval: "src/data/datasets/methods2test/processed/Qwen2_5-Coder-3B-Instruct/processed_eval.json"
    processed_test: "src/data/datasets/methods2test/processed/Qwen2_5-Coder-3B-Instruct/processed_test.json"