model:
  is_local: false
  model_dir: "src/outputs/Qwen2_5-Coder-3B-Instruct/checkpoint-29151"
  model_name_simple: "qwen"
  name: "Qwen/Qwen2.5-Coder-3B-Instruct"
  architecture: "causal"        
  quantization: false
  tokenizer_pad_token: "eos_token"
  tokenizer_padding_side: "left"

peft:
  is_peft: false
  type: "lora"
  r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
    - "lm_head"
  task_type: "CAUSAL_LM"

bnb:
    is_bnb: false
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    bnb_4bit_compute_dtype: "bfloat16"

infer:
    save_path: "src/evaluation/results/methods2test/Qwen2.5-Coder-3B-Instruct"
    pred_label: "FINETUNED" # "ORIGINAL | FINETUNED"

dataset:
  name: "methods2test"
  processed_path: "src/data/datasets/methods2test/processed/Qwen2_5-Coder-3B-Instruct/processed_test.json"
  need_special_processing: false
  special_processing_func: "dataset_preprocessing"
  split_seed: 42
  num_workers: 16
  batch_size: 384
  max_input_len: 720
  max_target_len: 256

misc:
  device: "cuda"
  notes: "experiment for Mistral7B with LoRA"
  log_dir: "logs/default"
  log_name: "QWEN.log"
