# customizable as needed. maybe explore multiple yaml files?

model:
  is_local: false
  model_dir: "./"
  name: "meta-llama/Llama-3.2-1B-Instruct"
  architecture: "causal"        
  quantization: false
  tokenizer_pad_token: "eos_token"
  tokenizer_padding_side: ""

peft:
  is_peft: false
  type: "lora"
  r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
    - "lm_head"
  task_type: "CAUSAL_LM"

bnb:
    is_bnb: false
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    bnb_4bit_compute_dtype: "bfloat16"

dataset:
  name: "mydataset"
  path: "src/data/datasets/methods2test/original/master_dataset.json"
  processed_path: ""
  need_special_processing: false
  special_processing_func: "llama_3_2_1B_template"
  need_tokenization: false
  tokenizer_func: "llama_3_2_1B_tokenize"
  split_seed: 42
  num_workers: 16
  batch_size: 4
  max_input_len: 720
  max_target_len: 256
  processed_train_location: "src/data/datasets/methods2test/processed/llama_3_2_1B/processed_train.json"
  processed_eval_location: "src/data/datasets/methods2test/processed/llama_3_2_1B/processed_eval.json"
  processed_test_location: "src/data/datasets/methods2test/processed/llama_3_2_1B/processed_test.json"
  tokenized_train_location: "src/data/datasets/methods2test/tokenized/llama_3_2_1B/tokenized_train.json"
  tokenized_eval_location: "src/data/datasets/methods2test/tokenized/llama_3_2_1B/tokenized_eval.json"
  tokenized_test_location: "src/data/datasets/methods2test/tokenized/llama_3_2_1B/tokenized_test.json"
  split: [0.9, 0.1, 0.1]

training:
  training_args_type: "SFTConfig"
  trainer_type: "SFTTrainer"
  output_dir: "src/outputs/llama_3_2_1B/"
  dataset_text_field: "prompt"
  num_train_epochs: 10
  learning_rate: 0.0002
  lr_scheduler_type: "linear"
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 32
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  logging_steps: 100
  optim: "adamw_8bit"
  weight_decay: 0.01
  warmup_steps: 1000
  report_to: "tensorboard"
  seed: 42
  bf16: true
  fp16: false
  dataloader_num_workers: 8
  ddp_find_unused_parameters: false
  dataloader_drop_last: true
  remove_unused_columns: false

misc:
  device: "cuda"
  notes: "experiment for Mistral7B with LoRA"
  log_dir: "logs/default"
  log_name: "meta-llama_3_2_1B.log"
