# customizable as needed. maybe explore multiple yaml files?

model:
  is_local: false
  model_dir: "./"
  name: "mistralai/Mistral-7B-Instruct-v0.3"
  architecture: "causal"           # or "seq2seq"
  quantization: false
  tokenizer_pad_token: "eos_token"
  tokenizer_padding_side: "right"

peft:
  is_peft: true
  type: "lora"
  r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
    - "lm_head"
  task_type: "CAUSAL_LM"

bnb:
    is_bnb: false
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    bnb_4bit_compute_dtype: "bfloat16"

dataset:
  name: "mydataset"
  path: "data/mydata.jsonl"
  processed_path: ""
  is_processed: false
  need_special_processing: false
  special_processing_func: ""
  split_seed: 42
  num_workers: 8
  batch_size: 4
  max_input_len: 512
  max_target_len: 256

training:
  training_args_type: "SFTConfig"
  trainer_type: "SFTTrainer"
  output_dir: "outputs/"
  num_train_epochs: 3
  learning_rate: 2e-4
  gradient_accumulation_steps: 2
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  logging_steps: 20
  report_to: ["tensorboard"]
  seed: 42

misc:
  device: "cuda"
  notes: "experiment for Mistral7B with LoRA"
  log_dir: "logs/default"
